In [74]:
#imports
from __future__ import division
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pylab as pl
import numpy as np
import seaborn as sns
import statsmodels.formula.api as smf
%matplotlib inline

In [75]:
data = pd.read_csv("../dataset/T807_Master_Data.csv")
data.head()

,SubNum,initials,dx,Sex,referral source,In UDS?,Doc visit complete?,Amyvid dose ordered?,T807 dose ordered?,Amyvid Complete?,...,MRI Safety Read,AMYVID PET RESULT,SUVr,Amyvid amount Injected (ml),Amyvid dose Injected (mCi),Minutes post injection for scan (Amyvid),T807 amount Injected (ml),T807 dose Injected (mCi),Minutes post injection for scan (T807),T807
0,T807_001,EM,mTBI,M,Gandy,Y,Y,Y,Y,Y,...,small lipoma suggested within the right fronta...,negative,1.075,NaN,10,50,NaN,10.10,80.0,negative
1,T807_002,SM,mTBI,M,self-referral,Y,Y,Y,Y,Y,...,normal,negative,0.929,2.01,9.8,51,2.54,10.20,80.0,positive
2,T807_003,KG,HC,M,Dickstein,Y,Y,Y,Y,Y,...,scattered periventricular and subcort T2/FLAIR...,negative,0.89,NaN,9.9,49,NaN,10.20,83.0,negative
3,T807_004,BS,mTBI,M,Gandy,Y,Y,Y,Y,Y,...,normal,negative,0.829,NaN,10.3,54,NaN,10.12,79.0,negative
4,T807_005,GM,mTBI,M,hockey conference,Y,Y,Y,Y,Y,...,mild bilateral subcort and perivent T2/FLAIR W...,negative,0.985,NaN,8.33,49,NaN,10.03,74.0,negative

In [76]:
data.shape

(36, 133)

In [77]:
data.columns

Index([u'SubNum', u'initials', u'dx', u'Sex', u'referral source', u'In UDS?',
       u'Doc visit complete?', u'Amyvid dose ordered?', u'T807 dose ordered?',
       u'Amyvid Complete?',
       ...
       u'MRI Safety Read ', u'AMYVID PET RESULT', u'SUVr',
       u'Amyvid amount Injected (ml)', u'Amyvid dose Injected (mCi)',
       u'Minutes post injection for scan (Amyvid)',
       u'T807 amount Injected (ml)', u'T807 dose Injected (mCi)',
       u'Minutes post injection for scan (T807)', u'T807'],
      dtype='object', length=133)

In [78]:
df = data[['MoCA','BDI-II','Age when seen','Education','Categorical # of TBIs','Rivermead','LNS_SS','Similarities_SS','NPI','Coding_SS','Categorical # of TBIs']]

In [81]:
df.mean()

MoCA                     24.138889
BDI-II                   15.472222
Age when seen            49.666667
Education                15.055556
Categorical # of TBIs     2.500000
Rivermead                29.967742
LNS_SS                    9.212121
Similarities_SS          11.800000
NPI                       9.193548
Categorical # of TBIs     2.500000
dtype: float64

In [82]:
df.fillna(df.mean())

,MoCA,BDI-II,Age when seen,Education,Categorical # of TBIs,Rivermead,LNS_SS,Similarities_SS,NPI,Coding_SS,Categorical # of TBIs
0,26,41,49,16.0,2,39.0,NaN,11.0,20.0,NA,2
1,28,24,39,16.0,3,46.0,10.0,14.0,14.0,11,3
2,24,5,53,15.5,0,NaN,10.0,11.0,0.0,11,0
3,25,4,53,16.0,5,18.0,9.0,11.0,4.0,12,5
4,27,12,59,13.0,5,34.0,7.0,10.0,8.0,8,5
5,28,7,39,14.0,5,46.0,9.0,13.0,6.0,9,5
6,25,11,57,13.0,1,31.0,9.0,11.0,12.0,11,1
7,28,30,45,16.0,2,13.0,11.0,11.0,4.0,8,2
8,28,8,62,12.0,1,14.0,12.0,11.0,1.0,13,1
9,29,2,49,15.0,0,NaN,14.0,17.0,4.0,16,0
10,27,8,46,18.0,2,18.0,10.0,14.0,4.0,10,2
11,25,5,63,15.5,4,22.0,8.0,13.0,12.0,5,4
12,27,28,59,16.0,4,49.0,9.0,14.0,23.0,9,4
13,28,12,45,16.0,0,NaN,9.0,16.0,NaN,12,0
14,25,15,46,12.0,3,16.0,11.0,14.0,13.0,11,3
15,23,4,54,14.0,2,35.0,9.0,11.0,12.0,12,2
16,23,23,63,15.0,2,32.0,9.0,15.0,3.0,11,2
17,23,33,68,16.0,1,60.0,9.0,13.0,10.0,9,1
18,21,33,49,16.0,2,49.0,9.0,9.0,8.0,7,2
19,24,9,56,16.0,2,26.0,11.0,15.0,13.0,13,2
20,26,3,57,15.0,0,NaN,8.0,10.0,NaN,9,0
21,20,12,45,18.0,5,29.0,9.0,14.0,5.0,10,5
22,12,4,74,16.0,5,10.0,NaN,11.0,NaN,10,5
23,25,3,39,14.0,4,3.0,9.0,12.0,NaN,9,4
24,21,18,45,16.0,2,29.0,9.0,12.0,11.0,10,2
25,19,34,44,16.0,5,61.0,5.0,8.0,11.0,6,5
26,20,36,43,16.0,5,28.0,9.0,8.0,16.0,7,5
27,29,0,42,16.0,0,NaN,10.0,12.0,NaN,12,0
28,21,32,32,14.0,1,48.0,6.0,8.0,14.0,3,1
29,28,13,31,13.0,4,24.0,11.0,10.0,13.0,9,4
30,24,14,46,15.0,2,24.0,9.0,11.0,5.0,9,2
31,16,4,79,16.0,1,0.0,NaN,10.0,4.0,9,1
32,22,22,35,12.0,1,36.0,8.0,12.0,11.0,4,1
33,24,20,55,16.0,5,35.0,10.0,9.0,13.0,5,5
34,22,24,32,15.0,2,45.0,7.0,12.0,11.0,8,2
35,26,4,35,13.0,2,9.0,9.0,NaN,0.0,6,2